// This file is auto-generated by @hey-api/openapi-ts

export type StopSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulation/stop"
}

export type StopSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type StopSimulationResponse = StopSimulationResponses[keyof StopSimulationResponses]

export type StartSimulationData = {
    body: string
    path?: never
    query?: never
    url: "/simulation/start"
}

export type StartSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type StartSimulationResponse = StartSimulationResponses[keyof StartSimulationResponses]

export type SetSpeedData = {
    body?: never
    path?: never
    query: {
        factor: number
    }
    url: "/simulation/control/speed"
}

export type SetSpeedResponses = {
    /**
     * OK
     */
    200: string
}

export type SetSpeedResponse = SetSpeedResponses[keyof SetSpeedResponses]

export type ResumeSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulation/control/resume"
}

export type ResumeSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type ResumeSimulationResponse = ResumeSimulationResponses[keyof ResumeSimulationResponses]

export type PauseSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulation/control/pause"
}

export type PauseSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type PauseSimulationResponse = PauseSimulationResponses[keyof PauseSimulationResponses]

export type GetAllLogsData = {
    body?: never
    path?: never
    query?: never
    url: "/simulation/logs"
}

export type GetAllLogsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: Array<string>
    }
}

export type GetAllLogsResponse = GetAllLogsResponses[keyof GetAllLogsResponses]

export type GetLogsForAgentData = {
    body?: never
    path: {
        agentName: string
    }
    query?: never
    url: "/simulation/logs/{agentName}"
}

export type GetLogsForAgentResponses = {
    /**
     * OK
     */
    200: Array<string>
}

export type GetLogsForAgentResponse = GetLogsForAgentResponses[keyof GetLogsForAgentResponses]

export type ClientOptions = {
    baseUrl: "http://localhost:8081" | (string & {})
}
