// This file is auto-generated by @hey-api/openapi-ts

export type StopSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulate/stop"
}

export type StopSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type StopSimulationResponse = StopSimulationResponses[keyof StopSimulationResponses]

export type StartSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulate/start"
}

export type StartSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type StartSimulationResponse = StartSimulationResponses[keyof StartSimulationResponses]

export type SetSpeedData = {
    body?: never
    path?: never
    query: {
        factor: number
    }
    url: "/simulate/control/speed"
}

export type SetSpeedResponses = {
    /**
     * OK
     */
    200: string
}

export type SetSpeedResponse = SetSpeedResponses[keyof SetSpeedResponses]

export type ResumeSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulate/control/resume"
}

export type ResumeSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type ResumeSimulationResponse = ResumeSimulationResponses[keyof ResumeSimulationResponses]

export type PauseSimulationData = {
    body?: never
    path?: never
    query?: never
    url: "/simulate/control/pause"
}

export type PauseSimulationResponses = {
    /**
     * OK
     */
    200: string
}

export type PauseSimulationResponse = PauseSimulationResponses[keyof PauseSimulationResponses]

export type GetLogsData = {
    body?: never
    path?: never
    query?: never
    url: "/simulate/logs"
}

export type GetLogsResponses = {
    /**
     * OK
     */
    200: Array<string>
}

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses]

export type ClientOptions = {
    baseUrl: "http://localhost:8081" | (string & {})
}
